# ワークフローの名前
name: Deploy to Staging

# トリガー: stgブランチにプッシュ（マージ）された時
on:
  push:
    branches:
      - stg

# 実行するジョブ
jobs:
  deploy:
    # 実行環境
    runs-on: ubuntu-latest

    # 実行するステップ
    steps:
      - name: SSH into STG server and deploy
        # SSH接続とコマンド実行のためのアクション
        uses: appleboy/ssh-action@v1.0.3

        # アクションに渡す設定 (GitHub Secretsから読み込む)
        with:
          host: ${{ secrets.STG_SSH_HOST }}
          username: ${{ secrets.STG_SSH_USER }}
          key: ${{ secrets.STG_SSH_KEY }}

          # STGサーバー上で実行するコマンド
          script:
            # 1. アプリのディレクトリに移動 (STG環境のパス)
            cd /var/www/stg-cross-diary/cross-diary
            
            # 2. stgブランチの最新コードをプル
            git pull origin stg
            
            # 3. 依存関係のインストール (package.json変更に備える)
            npm install
            
            # 4. npx を使ってローカルのpm2でアプリを再起動
            npx pm2 restart xdiary-app-stg
